### ISSUE TITLE
Increase resolution.

### ISSUE THREAD

**Issue by bradley-varol** [wavesurfer-js/wavesurfer.js#1468] opened 2018-09-26 21:24 UTC
I've noticed that if I load wavesurfer with the page zoomed in, the resolution is much higher.
Is there any way to increase the resolution of the waveform to remove the blurriness around the bars as you can see here.?
![image](https://user-images.githubusercontent.com/19194140/46110233-ed1e0900-c1da-11e8-8d87-f2bae66bf88c.png)

**Comment by thijstriemstra** [comment] 2018-09-29 00:31
is this a duplicate of #1454 @bradley-varol?

**Comment by bradley-varol** [comment] 2018-09-29 18:00
> is this a duplicate of #1454 @bradley-varol?

Sorry, I tried to find that issue before but couldn't so I made this one. I'll delete the old one.

**Comment by danielcampagne** [comment] 2019-02-04 01:37
Anybody found a solution?

**Comment by entonbiba** [comment] 2021-01-25 02:04
@danielcampagne @bradley-varol you can add the `responsive: true` option to auto resize, maybe we can look into redrawing the wave with better resolution on resize as well. at the moment I think it only takes care of the width but not width and height of each peak.

**Comment by entonbiba** [comment] 2021-01-25 02:11
@danielcampagne @bradley-varol you can add the following options `responsive: true, forceDecode: true` option to auto resize, 

https://www.entonbiba.com/lab/wavesurfer/1468.html

**Closed** 2023-02-26 09:30 UTC
Labels: question
