### ISSUE TITLE
Sync with playing audio element

### ISSUE THREAD

**Issue by ibcs01** [wavesurfer-js/wavesurfer.js#1780] opened 2019-10-22 20:32 UTC
We are using Vue and we placed the audio element in the background so it keeps playing while browsing the site. When we return to the initial page from which the playback was started, we would like to reconnect WaveSurfer to the sound as if you never left the page. Hence showing the player in an active state with an active progress bar at the exact position of the playing file at that moment.

We use the WaveSurfer on that page with no special settings, besides an existing audio element which we call with document.getElementById('myElement') and then pass to the wavesurfer.load function. We can connect with the audio element by passing it to the load function, but it resets the playing sate and that's not desirable.

When browsing to other pages, WaveSurfer  is completely unset and only the audio element is preserved. Is there a way we can smoothly reconnect to this playing audio element when we return to the page with the player on it?

Great work by the way!

**Comment by thijstriemstra** [comment] 2019-10-23 13:01
looks like a duplicate of #1766?

**Comment by thijstriemstra** [comment] 2019-10-23 16:45
what does your current wavesurfer config look like?

**Comment by ibcs01** [comment] 2019-10-23 22:09
See the code snippet below. We load the waveform first without loading the audio file. When clicking the play button; startPlaying() is called and loads the file to an existing audio element. And there lays our issue; the sound is stopped when calling wavesurfer.load(elemAudio, peaks, false, duration). What we are looking for is a solution to hook to the playing sound without stopping it.

`// Init vars
var urlAudio = '/folder/file.mp3';
var duration = 20;
var peaks = [0.0, 0.0, -0.33620689655172414, 0.31896551724137934, -0.3620689655172414, 0.35344827586206895, -0.4051724137931034, 0.33620689655172414, -0.39655172413793105, 0.3103448275862069, -0.3793103448275862, 0.31896551724137934, -0.3275862068965517, 0.33620689655172414, -0.3620689655172414, 0.33620689655172414, -0.3793103448275862, 0.35344827586206895, -0.35344827586206895, 0.33620689655172414, -0.35344827586206895, 0.3103448275862069, -0.35344827586206895, 0.3275862068965517, -0.3706896551724138, 0.31896551724137934, -0.33620689655172414, 0.3017241379310345, -0.33620689655172414, 0.33620689655172414, -0.35344827586206895, 0.33620689655172414, -0.33620689655172414, 0.3620689655172414, -0.3448275862068966, 0.33620689655172414, -0.3706896551724138, 0.3448275862068966, -0.4051724137931034, 0.31896551724137934, -0.25, 0.27586206896551724, -0.15517241379310345, 0.14655172413793102];

// Create wavesurfer object
this.wavesurfer = WaveSurfer.create({
    container: '#waveform',
    audioContext: {},
    removeMediaElementOnDestroy: false,
    backend: 'MediaElement',
    mediaType: 'audio',
    duration: duration,
    barHeight: 1,
    normalize: true,
});

// Load waveform without changing audio element
this.wavesurfer.backend.setPeaks(peaks, duration);
this.wavesurfer.drawBuffer();

/**
 *  And when clicking the play button it calls
 */
function startPlaying()
{
    // We use an external audio element
    var elemAudio = document.getElementById("mainAudio");
    elemAudio.src = urlAudio;
    elemAudio.load();

    // Load to player and start playing
    this.wavesurfer.load(elemAudio, peaks, false, duration);
    this.wavesurfer.playPause();
}
// Init vars
var urlAudio = '/folder/file.mp3';
var duration = 20;
var peaks = [0.0, 0.0, -0.33620689655172414, 0.31896551724137934, -0.3620689655172414, 0.35344827586206895, -0.4051724137931034, 0.33620689655172414, -0.39655172413793105, 0.3103448275862069, -0.3793103448275862, 0.31896551724137934, -0.3275862068965517, 0.33620689655172414, -0.3620689655172414, 0.33620689655172414, -0.3793103448275862, 0.35344827586206895, -0.35344827586206895, 0.33620689655172414, -0.35344827586206895, 0.3103448275862069, -0.35344827586206895, 0.3275862068965517, -0.3706896551724138, 0.31896551724137934, -0.33620689655172414, 0.3017241379310345, -0.33620689655172414, 0.33620689655172414, -0.35344827586206895, 0.33620689655172414, -0.33620689655172414, 0.3620689655172414, -0.3448275862068966, 0.33620689655172414, -0.3706896551724138, 0.3448275862068966, -0.4051724137931034, 0.31896551724137934, -0.25, 0.27586206896551724, -0.15517241379310345, 0.14655172413793102];

// Create wavesurfer object
this.wavesurfer = WaveSurfer.create({
    container: '#waveform',
    audioContext: {},
    removeMediaElementOnDestroy: false,
    backend: 'MediaElement',
    mediaType: 'audio',
    responsive: true,
    duration: duration,
    msDisplayMax: 0,
    barGap: 1, // sven
    barWidth: 2,
    cursorWidth: 2,
    cursorColor: '#fff',
    fillParent: true, // Whether to fill the entire container or draw only according to minPxPerSec.
    barHeight: 1,
    minPxPerSec: 1, // Minimum number of pixels per second of audio.
    height: 90,
    autoCenter: true,
    debug: false,
    normalize: true,
    waveColor: '#666',
    progressColor: '#65bece',
    hideScrollbar: false,
    loopSelection: false
});

// Load waveform without changing audio element
this.wavesurfer.backend.setPeaks(peaks, duration);
this.wavesurfer.drawBuffer();

/**
 *  And when clicking the play button it calls
 */
function startPlaying()
{
    // We use an external audio element
    var elemAudio = document.getElementById("mainAudio");
    elemAudio.src = urlAudio;
    elemAudio.load();

    // Load to player and start playing
    this.wavesurfer.load(elemAudio, peaks, false, duration);
    this.wavesurfer.playPause();
}
`

**Comment by thijstriemstra** [comment] 2019-10-23 22:53
@ibcs01 there's a `media.load()` call in the `MediaElement` backend. Try commenting that out because it supposed to reset everything..

**Comment by ibcs01** [comment] 2019-10-24 11:31
Tested that and it does not solve the problem. 

It turns out that `_load(media, peaks)` in mediaelement.js also calls `media.load()` (line 131). 

In the comment it says that peaks wont load if its not called. But that does not count in case of pre-rendered peaks i guess? So it might be an idea to make media.load that line optional?

**Comment by thijstriemstra** [comment] 2019-10-24 11:34
> It turns out that _load(media, peaks) in mediaelement.js also calls media.load() (line 131).

That's what I meant, yeah.

> So it might be an idea to make media.load that line optional?

If it improves things (or you), sure, sounds good.

**Comment by ibcs01** [comment] 2019-10-24 12:11
I will first test if it solves my problem. I will report back later.
Thanks!

**Comment by abrahamian** [comment] 2019-10-29 04:18
This is a duplicate of my issue #1704. I pushed some changes to the code in my fork, which is linked in that issue's discussion. Please see if it works for your use case.

**Closed** 2023-02-26 09:28 UTC
Labels: question, needs-update
