### ISSUE TITLE
Song not loaded when providing peaks

### ISSUE THREAD

**Issue by Guisch** [wavesurfer-js/wavesurfer.js#1414] opened 2018-07-18 17:29 UTC
Hey, I recently switch my project to server side generated waveform and it brings me a bug.
When peaks aren't provided, the 'ready' event fires when i call ```wavesurfer.load(url)```.
However, when peaks are provided, the 'ready' event isn't fired, and the song isn't loaded until I use play function or interact with the waveform.
So I tried to understand why, and I found this. When peaks are provided, it loads the song only when 'interact' event is fired.

https://github.com/katspaugh/wavesurfer.js/blob/00b1e8185c9987ebaa950188b9bc060b31967626/src/wavesurfer.js#L1236

Shouldn't we replace this line by just a ```return load();``` ?

**Comment by danielkrich** [comment] 2018-10-17 13:42
Is this going to be fixed anytime soon? Is there a workaround for now?

**Comment by Guisch** [comment] 2018-10-17 14:42
Made this workaround, works fine for me

```
function load(url) {
    wavesurfer.backend.setPeaks([]);
    wavesurfer.drawBuffer();
    wavesurfer.getArrayBuffer(url, data => wavesurfer.loadArrayBuffer(data));
}
```

**Comment by thijstriemstra** [comment] 2018-11-17 19:54
Looks like duplicate of #1244

**Comment by yogisalomo** [comment] 2019-02-26 08:47
hi @Guisch , with your workaround I managed to fire waveform-ready event when providing peaks. However the values of the waveform became wrong. Could you please explain a bit more on how to use your workaround? Do I still need to call the provided wavesurfer.load function? 

Thanks for sharing your workaround.

**Comment by Guisch** [comment] 2019-02-26 11:12
Hey !
> Could you please explain a bit more on how to use your workaround?
The workaround is meant to replace only the load function, so usage is the same.
> Do I still need to call the provided wavesurfer.load function?
No
>However the values of the waveform became wrong
Please make sure that the data you are providing is well formated. I've made a simple wrapper that output correct data if you want: https://github.com/Guisch/simpleWaveformJs

**Comment by yogisalomo** [comment] 2019-02-28 01:43
Thank you very much for your response. The wrapper seems really useful as well, so thanks for that too! @Guisch

**Comment by thijstriemstra** [comment] 2019-03-06 21:42
@Guisch that looks like a useful tool. maybe we can include it in wavesurfer.js so more people can help maintain it and use it?

**Comment by Guisch** [comment] 2019-03-07 14:05
I need to do some edit first but Yeah why not

**Comment by thijstriemstra** [comment] 2019-03-07 14:33
Awesome, looking forward to the PR.

**Comment by entonbiba** [comment] 2021-01-26 00:46
@thijstriemstra this still happens on latest version?

**Comment by thijstriemstra** [comment] 2021-01-26 00:51
no idea, please don't @ me on every ticket ;)

**Comment by sundayz** [comment] 2021-01-26 00:53
The 'ready' event acts weird sometimes. At some stage we should make `load` return a Promise and that might clean things up.

This specific issue is a duplicate because it seems to be about `'ready'` only triggering once `'interaction'` is emitted when using the WebAudio backend. I dont know why thats the case but my opinion is most likely a legacy thing to make sure playback only starts on user interaction but it doesnt actually help anymore.

**Comment by entonbiba** [comment] 2021-01-26 01:08
> no idea, please don't @ me on every ticket ;)
you come up first meant it for Guisch lol

**Comment by Guisch** [comment] 2021-01-27 22:33
Hey I'm not using wavesurfer anymore and to be honest this issue is 1.5 years old so my knowledge may vary.
I may be wrong but From what I remember  `load` function is firing the `ready` event. So you just should call `load` I guess. 
As previously said, that's what I ended up doing:
```js
function load(url, peaks) {
    wavesurfer.backend.setPeaks(peaks);
    wavesurfer.drawBuffer();
    wavesurfer.getArrayBuffer(url, data => wavesurfer.loadArrayBuffer(data));
}
```

**Closed** 2023-02-26 10:22 UTC
Labels: bug
